package com.dialog.lvis.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-12T16:07:53.155+11:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://webservices.lvis.dialog.com/", name = "MARSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MARSSoap {

    @WebResult(name = "requestResult", targetNamespace = "http://webservices.lvis.dialog.com/")
    @RequestWrapper(localName = "request", targetNamespace = "http://webservices.lvis.dialog.com/", className = "com.dialog.lvis.webservices.Request")
    @WebMethod(action = "http://webservices.lvis.dialog.com/request")
    @ResponseWrapper(localName = "requestResponse", targetNamespace = "http://webservices.lvis.dialog.com/", className = "com.dialog.lvis.webservices.RequestResponse")
    public com.dialog.lvis.webservices.MARSResponse request(
        @WebParam(name = "pRequest", targetNamespace = "http://webservices.lvis.dialog.com/")
        com.dialog.lvis.webservices.MARSRequest pRequest
    );
}
